import type { Report, Status } from "../types";

export const COMMENT_MARKER = "<!-- solana-sdk-doctor-report -->";
const ICON: Record<Status, string> = { pass: "✅", info: "ℹ️", warn: "⚠️", fail: "❌" };

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

export function renderMarkdown(report: Report): string {
  const s = report.summary;
  const out: string[] = [COMMENT_MARKER];
  const headline = s.fail > 0 ? "❌ SDK drift detected" : s.warn > 0 ? "⚠️ SDK drift warnings" : "✅ No blocking SDK drift";
  out.push(`### 🩺 Solana SDK Doctor — ${headline}`);
  out.push("");
  out.push(`**${s.fail}** fail · **${s.warn}** warn · **${s.info}** info · **${s.pass}** pass — ${report.mode} mode, ${report.rulesLoaded} rules, ${report.manifests.length} package.json`);
  if (report.rpc) {
    const bits = [`provider \`${report.rpc.provider}\``, `\`${report.rpc.url}\``];
    if (report.rpc.slot !== undefined) bits.push(`slot **${report.rpc.slot}**`);
    if (report.rpc.latencyMs !== undefined) bits.push(`latency **${report.rpc.latencyMs}ms**`);
    if (report.rpc.onChainQueried !== undefined) bits.push(`on-chain addrs **${report.rpc.onChainQueried}**`);
    out.push("");
    out.push(`RPC: ${bits.join(" · ")}`);
  }
  out.push("");
  if (report.findings.length === 0) {
    out.push("_No known Solana/oracle SDKs detected._");
    return out.join("\n") + "\n";
  }
  out.push("| | Rule | Package | Finding | Evidence |");
  out.push("|---|---|---|---|---|");
  for (const f of report.findings) {
    const where = report.manifests.length > 1 ? `<br><sub>${f.manifest}</sub>` : "";
    const pkg = (f.package ? `\`${f.package}${f.version ? "@" + f.version : ""}\`` : "_source_") + where;
    const ev =
      f.probe.source !== "none"
        ? `${f.probe.source}: ${f.probe.detail ?? ""}`
        : f.locations.length
          ? `${f.locations.length} call site(s)`
          : f.ruleId === "-" ? "" : "static rule";
    out.push(`| ${ICON[f.status]} | ${f.ruleId === "-" ? "—" : `\`${f.ruleId}\``} | ${pkg} | ${esc(f.title)} | ${esc(ev)} |`);
  }
  const problems = report.findings.filter((f) => f.status !== "pass");
  if (problems.length) {
    out.push("");
    out.push("<details><summary>Details & fixes</summary>");
    out.push("");
    for (const f of problems) {
      out.push(`#### ${ICON[f.status]} \`${f.ruleId}\` — ${f.title}`);
      out.push(`_${f.manifest}_`);
      out.push("");
      out.push(f.summary);
      out.push("");
      for (const l of f.locations.slice(0, 10)) out.push(`- \`${l.file}:${l.line}\`${l.mitigated ? " (mitigated)" : ""} — \`${esc(l.snippet)}\``);
      if (f.note) out.push(`- **Note:** ${f.note}`);
      out.push(`- **Fix:** ${f.fix}`);
      if (f.docs.length) out.push(`- **Docs:** ${f.docs.map((d) => `<${d}>`).join(", ")}`);
      out.push("");
    }
    out.push("</details>");
  }
  out.push("");
  out.push(`<sub>Generated by ${report.tool.name} v${report.tool.version} at ${report.generatedAt}</sub>`);
  return out.join("\n") + "\n";
}
